version: '3.7'
services:
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_reservation: 300m
    ports:
      - "9411:9411"
    networks:
      - e-commerce
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    restart: always


  rabbitmq:
    image: rabbitmq:3.8.12-management
    mem_reservation: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - e-commerce

  eureka-server:

    container_name: eureka-server
    image: eureka-server
    mem_reservation: 700m
    ports:
      - "8761:8761"
    networks:
      - e-commerce
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq


  product-service:

    container_name: product-service
    image: product-service
    mem_reservation: 700m
    ports:
      - "8000:8000"
    networks:
      - e-commerce
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq



  api-gateway:
    container_name: api-gateway
    image: api-gateway
    mem_reservation: 700m
    ports:
      - "8765:8765"
    networks:
      - e-commerce
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit



networks:
  e-commerce: